=== kit-data-manager/base/src/resources/metadata/schema/dataorganization/dataorganization.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://kitdatamanager.net/dama/dataorganization" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:do="http://kitdatamanager.net/dama/dataorganization">


	<xs:element name="dataOrganization">
		<xs:annotation>
			<xs:documentation xml:lang="en">The KIT Data Manager (KIT DM) data organization describes the structure of the digital object data content. The content is described by hierarchical nodes, which represent either the file and directory tree or other hierarchical views on the data.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="digitalObjectId" type="xs:string"/>
				<xs:element name="view" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="root" type="do:node">
								<xs:annotation>
									<xs:documentation xml:lang="en">The root node does not have a name, such that the name element of the root node will be ignored and should be empty. This approach is chosen for the sake of simplicity, otherwise the schema would contain two very similar node types: rootnode and node, which only differ in the name element.
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" default="default"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="onlyUniqueViewNamesAllowed">
			<xs:selector xpath="do:view"/>
			<xs:field xpath="@name"/>
 		</xs:unique>
	</xs:element>


	<xs:complexType name="attributes">
		<xs:annotation>
			<xs:documentation xml:lang="en">The attributes are key-value pairs of strings.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element maxOccurs="unbounded" minOccurs="1" name="attribute">
				<xs:complexType>
					<xs:all>
						<xs:element name="key"   type="xs:string"/>
						<xs:element name="value" type="xs:string"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="node">
		<xs:annotation>
			<xs:documentation xml:lang="en">Each node can contain attributes to describe the properties or content of the node. Each node can contain an arbitrary number of nodes, such that an hierarchical structure can be expressed.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name"            type="xs:string"/>
			<xs:element name="logicalFileName" type="xs:string"     minOccurs="0"/>
			<xs:element name="description"     type="xs:string"     minOccurs="0"/>
			<xs:element name="attributes"      type="do:attributes" minOccurs="0"/>
			<xs:element name="children"                             minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="child" type="do:node" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== kit-data-manager/base/src/resources/metadata/schema/dataorganization/examples/valid-nested-nodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataOrganization xmlns="http://kitdatamanager.net/dama/dataorganization"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://kitdatamanager.net/dama/dataorganization ../dataorganization.xsd">
	<digitalObjectId>b4251d93-ab4f-4410-93f2-8c6859539f69</digitalObjectId>
  <view>
    <root>
        <name>Node name 1</name>
        <children>
            <child>
                <name>Node name 2</name>
                <children>
                    <child>
                        <name>Node name 3</name>
                        <children>
                            <child>
                                <name>Node name 4</name>
                                <logicalFileName>file:///mnt/archive/storage1/234/6324763.png</logicalFileName>
                            </child>
                            <child>
                                <name>Node name 5</name>
                                <logicalFileName>file:///mnt/archive/storage1/234/6324764.png</logicalFileName>
                            </child>
                        </children>
                    </child>
                </children>
            </child>

            <child>
                <name>Node name 6</name>
                <children>
                    <child>
                        <name>Node name 7</name>
                    </child>
                    <child>
                        <name>Node name 8</name>
                        <children>
                            <child>
                                <name>Node name 9</name>
                                <logicalFileName>file:///mnt/archive/storage1/234/6324762.png</logicalFileName>
                            </child>
                        </children>
                    </child>
                    <child>
                        <name>Node name 10</name>
                    </child>
                    <child>
                        <name>Node name 11</name>
                        <children>
                            <child>
                                <name>Node name 12</name>
                                <children>
                                    <child>
                                        <name>Node name 13</name>
                                        <logicalFileName>file:///mnt/archive/storage1/234/6324.png</logicalFileName>
                                    </child>
                                    <child>
                                        <name>Node name 14</name>
                                        <children>
                                            <child>
                                                <name>Node name 15</name>
                                                <logicalFileName>file:///mnt/archive/storage1/234/6.png</logicalFileName>
                                            </child>
                                            <child>
                                                <name>Node name 16</name>
                                                <logicalFileName>file:///mnt/archive/storage1/234/63.png</logicalFileName>
                                            </child>
                                        </children>
                                    </child>
                                    <child>
                                        <name>Node name 17</name>
                                        <logicalFileName>file:///mnt/archive/storage1/234/63.png</logicalFileName>
                                    </child>
                                    <child>
                                        <name>Node name 18</name>
                                        <logicalFileName>file:///mnt/archive/storage1/234/63.png</logicalFileName>
                                    </child>
                                </children>
                            </child>
                            <child>
                                <name>Node name 19</name>
                            </child>
                        </children>
                    </child>
                </children>
            </child>
        </children>
    </root>
	</view>
</dataOrganization>

=== kit-data-manager/base/Utils/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataOrganization xmlns="http://datamanager.kit.edu/dama/dataorganization" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://datamanager.kit.edu/dama/dataorganization http://datamanager.kit.edu/dama/dataorganization/2015-08/dataorganization.xsd">
    <digitalObjectId>3852284e-17d8-4bc2-a067-d75692a7c94e</digitalObjectId>
    <view xmlns:NS1="http://datamanager.kit.edu/dama/dataorganization" NS1:name="default">
        <root>
            <name/>
            <children>
                <child>
                    <name>Documentation</name>
                    <children>
                        <child>
                            <name>kitten.jpg</name>
                            <logicalFileName>http://ipelsdf1.lsdf.kit.edu/index.php/nav-res-research/nav-res-act-large-scale-data-managment</logicalFileName>
                        </child>
                    </children>
                </child>
            </children>
        </root>
    </view>
    <view xmlns:NS1="http://datamanager.kit.edu/dama/dataorganization" NS1:name="default">
        <root>
            <name/>
            <children>
                <child>
                    <name>custom_view.json</name>
                    <logicalFileName>file:/Users/jejkal/tmp/2016/4/10/admin/e861b2490b46f67bb6639fa24d78e41847c6d3d5/data/custom_view.json</logicalFileName>
                    <attributes>
                        <attribute>
                            <key>size</key>
                            <value>363</value>
                        </attribute>
                        <attribute>
                            <key>lastModified</key>
                            <value>1462884810000</value>
                        </attribute>
                        <attribute>
                            <key>directory</key>
                            <value>false</value>
                        </attribute>
                    </attributes>
                </child>
                <child>
                    <name>default_view.json</name>
                    <logicalFileName>file:/Users/jejkal/tmp/2016/4/10/admin/e861b2490b46f67bb6639fa24d78e41847c6d3d5/data/default_view.json</logicalFileName>
                    <attributes>
                        <attribute>
                            <key>size</key>
                            <value>1018</value>
                        </attribute>
                        <attribute>
                            <key>lastModified</key>
                            <value>1462884810000</value>
                        </attribute>
                        <attribute>
                            <key>directory</key>
                            <value>false</value>
                        </attribute>
                    </attributes>
                </child>
            </children>
        </root>
    </view>
    <view xmlns:NS1="http://datamanager.kit.edu/dama/dataorganization" NS1:name="default">
        <root>
            <name/>
            <children>
                <child>
                    <name>Measurement1</name>
                    <children>
                        <child>
                            <name>image0.tiff</name>
                            <logicalFileName>http://localhost:8080/webdav/1/image0.tiff</logicalFileName>
                        </child>
                        <child>
                            <name>readme.txt</name>
                            <logicalFileName>http://localhost:8080/webdav/1/readme.txt</logicalFileName>
                        </child>
                    </children>
                </child>
                <child>
                    <name>Mesaurement2</name>
                    <children>
                        <child>
                            <name>cent sign ¢, euro sign €, pound sign £</name>
                            <logicalFileName>http://localhost:8080/webdav/2/image1.tiff</logicalFileName>
                        </child>
                        <child>
                            <name>readme.txt</name>
                            <logicalFileName>http://localhost:8080/webdav/2/readme.txt</logicalFileName>
                        </child>
                    </children>
                </child>
            </children>
        </root>
    </view>
</dataOrganization>
